name: Build and deploy container to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: travelfusionregistry.azurecr.io
        username: ${{ secrets.TRAVELFUSIONREGISTRY_USERNAME_99C4 }}
        password: ${{ secrets.TRAVELFUSIONREGISTRY_PASSWORD_99C4 }}

    - name: Build and push image to ACR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: travelfusionregistry.azurecr.io/travelfusionlean:${{ github.sha }}

    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        registryUrl: travelfusionregistry.azurecr.io
        imageToDeploy: travelfusionregistry.azurecr.io/travelfusionlean:${{ github.sha }}
        containerAppName: TravelFusionApp
        resourceGroup: TravelFusionGroup
        subscriptionId: 65da915b-ac2e-4b71-a04c-ed5b7d222d15
