name: Build and deploy ASP.Net Core app to Azure Web App - travelfusionapp

on:
  push:
    branches:
      - master
    paths:
      - 'TravelFusionLean/TravelFusionLean/**'
      - '.github/workflows/travelfusionapp.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore, build and publish Blazor app
        run: |
          dotnet restore ./TravelFusionLean/TravelFusionLean/TravelFusionLean.csproj
          dotnet build ./TravelFusionLean/TravelFusionLean/TravelFusionLean.csproj --configuration Release
          dotnet publish ./TravelFusionLean/TravelFusionLean/TravelFusionLean.csproj --configuration Release --output ./publish

      - name: Upload Blazor artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blazor-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA980A5EE36748C3A2479D24E23A51E0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C2BD997D1871416F8608B81D8BB5B4D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35E1A0371F174346B4824FBF047CA82A }}

      - name: Deploy Blazor app to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travelfusionapp'
          slot-name: 'Production'
          package: .
