name: Build and deploy ASP.Net Core API to Azure Web App - travelfusionapi

on:
  push:
    branches:
      - master
    paths:
      - 'TravelFusionLean/TravelFusionLeanApi/**'
      - '.github/workflows/travelfusionapi.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore, build and publish API
        run: |
          dotnet restore ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj
          dotnet build ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release
          dotnet publish ./TravelFusionLean/TravelFusionLeanApi/TravelFusionLeanApi.csproj --configuration Release --output ./publish

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3DEA69A8CF04483E98A3395070743E5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95029A3FD0854135BABC22224EC2E755 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC7FEF1B6FA548C590ED77F6B665A037 }}

      - name: Deploy API to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'travelfusionapi'
          slot-name: 'Production'
          package: ./api-app
